// import * as LucideIcons from "lucide-react";

// const iconNames = [
//     "Activity",
//     "Airplay",
//     "AlertCircle",
//     "AlertTriangle",
//     "AlignCenter",
//     "AlignJustify",
//     "AlignLeft",
//     "AlignRight",
//     "Anchor",
//     "Aperture",
//     "Archive",
//     "ArrowDown",
//     "ArrowDownCircle",
//     "ArrowDownLeft",
//     "ArrowDownRight",
//     "ArrowLeft",
//     "ArrowLeftCircle",
//     "ArrowRight",
//     "ArrowRightCircle",
//     "ArrowUp",
//     "ArrowUpCircle",
//     "ArrowUpLeft",
//     "ArrowUpRight",
//     "AtSign",
//     "Award",
//     "BarChart",
//     "BarChart2",
//     "Battery",
//     "BatteryCharging",
//     "Bell",
//     "Bluetooth",
//     "Bold",
//     "Book",
//     "BookOpen",
//     "Bookmark",
//     "Box",
//     "Briefcase",
//     "Calendar",
//     "Camera",
//     "CameraOff",
//     "Cast",
//     "Check",
//     "CheckCircle",
//     "CheckSquare",
//     "ChevronDown",
//     "ChevronLeft",
//     "ChevronRight",
//     "ChevronUp",
//     "ChevronsDown",
//     "ChevronsLeft",
//     "ChevronsRight",
//     "ChevronsUp",
//     "Chrome",
//     "Circle",
//     "Clipboard",
//     "Clock",
//     "Cloud",
//     "CloudDrizzle",
//     "CloudLightning",
//     "CloudOff",
//     "CloudRain",
//     "CloudSnow",
//     "Code",
//     "Codepen",
//     "Codesandbox",
//     "Coffee",
//     "Columns",
//     "Command",
//     "Compass",
//     "Copy",
//     "CornerDownLeft",
//     "CornerDownRight",
//     "CornerLeftDown",
//     "CornerLeftUp",
//     "CornerRightDown",
//     "CornerRightUp",
//     "CornerUpLeft",
//     "CornerUpRight",
//     "Cpu",
//     "CreditCard",
//     "Crop",
//     "Crosshair",
//     "Database",
//     "Delete",
//     "Disc",
//     "Divide",
//     "DivideCircle",
//     "DivideSquare",
//     "DollarSign",
//     "Download",
//     "Dribbble",
//     "Droplet",
//     "Edit",
//     "Edit2",
//     "Edit3",
//     "ExternalLink",
//     "Eye",
//     "EyeOff",
//     "Facebook",
//     "FastForward",
//     "Feather",
//     "Figma",
//     "File",
//     "FileMinus",
//     "FilePlus",
//     "FileText",
//     "Film",
//     "Filter",
//     "Flag",
//     "Folder",
//     "FolderMinus",
//     "FolderPlus",
//     "Framer",
//     "Frown",
//     "Fullscreen",
//     "Geo",
//     "Gift",
//     "GitBranch",
//     "GitCommit",
//     "GitMerge",
//     "GitPullRequest",
//     "GitHub",
//     "Gitlab",
//     "Globe",
//     "Grid",
//     "HardDrive",
//     "Hash",
//     "Headphones",
//     "Heart",
//     "HelpCircle",
//     "Hexagon",
//     "Home",
//     "Image",
//     "Inbox",
//     "Info",
//     "Instagram",
//     "Italic",
//     "Key",
//     "Layers",
//     "Layout",
//     "LifeBuoy",
//     "Link",
//     "Link2",
//     "Linkedin",
//     "List",
//     "Loader",
//     "Lock",
//     "LogIn",
//     "LogOut",
//     "Mail",
//     "Map",
//     "MapPin",
//     "Maximize",
//     "Maximize2",
//     "Meh",
//     "Menu",
//     "MessageCircle",
//     "MessageSquare",
//     "Mic",
//     "MicOff",
//     "Minimize",
//     "Minimize2",
//     "Minus",
//     "MinusCircle",
//     "MinusSquare",
//     "Monitor",
//     "Moon",
//     "MoreHorizontal",
//     "MoreVertical",
//     "MousePointer",
//     "Move",
//     "Music",
//     "Navigation",
//     "Navigation2",
//     "Octagon",
//     "Package",
//     "Paperclip",
//     "Pause",
//     "PauseCircle",
//     "PenTool",
//     "Percent",
//     "Phone",
//     "PhoneCall",
//     "PhoneForwarded",
//     "PhoneIncoming",
//     "PhoneMissed",
//     "PhoneOff",
//     "PhoneOutgoing",
//     "PieChart",
//     "Play",
//     "PlayCircle",
//     "Plus",
//     "PlusCircle",
//     "PlusSquare",
//     "Pocket",
//     "Power",
//     "Printer",
//     "Radio",
//     "RefreshCcw",
//     "RefreshCw",
//     "Repeat",
//     "Rewind",
//     "RotateCcw",
//     "RotateCw",
//     "Rss",
//     "Save",
//     "Scissors",
//     "Search",
//     "Send",
//     "Server",
//     "Settings",
//     "Share",
//     "Share2",
//     "Shield",
//     "ShieldOff",
//     "ShoppingBag",
//     "ShoppingCart",
//     "Shuffle",
//     "Sidebar",
//     "SkipBack",
//     "SkipForward",
//     "Slack",
//     "Slash",
//     "Sliders",
//     "Smartphone",
//     "Smile",
//     "Speaker",
//     "Square",
//     "Star",
//     "StopCircle",
//     "Sun",
//     "Sunrise",
//     "Sunset",
//     "Tablet",
//     "Tag",
//     "Target",
//     "Terminal",
//     "Thermometer",
//     "ThumbsDown",
//     "ThumbsUp",
//     "ToggleLeft",
//     "ToggleRight",
//     "Tool",
//     "Trash",
//     "Trash2",
//     "Trello",
//     "TrendingDown",
//     "TrendingUp",
//     "Triangle",
//     "Truck",
//     "Tv",
//     "Twitch",
//     "Twitter",
//     "Type",
//     "Umbrella",
//     "Underline",
//     "Unlock",
//     "Upload",
//     "UploadCloud",
//     "User",
//     "UserCheck",
//     "UserMinus",
//     "UserPlus",
//     "UserX",
//     "Users",
//     "Video",
//     "VideoOff",
//     "Voicemail",
//     "Volume",
//     "Volume1",
//     "Volume2",
//     "VolumeX",
//     "Watch",
//     "Wifi",
//     "WifiOff",
//     "Wind",
//     "X",
//     "XCircle",
//     "XOctagon",
//     "XSquare",
//     "Youtube",
//     "Zap",
//     "ZapOff",
//     "ZoomIn",
//     "ZoomOut"
// ]


// export const Iconlists = iconNames.map((name, index) => {
//     const IconComponent = LucideIcons[name];

//     if (!IconComponent) {
//         console.error(`Lucide icon "${name}" not found.`);
//         return null;
//     }

//     return {
//         id: index,
//         name,
//         icon: LucideIcons[name]
//     };
// });

import React from 'react';
import * as LucideIcons from 'lucide-react';

export const Iconlists = [
    { icon: LucideIcons.Activity },
    { icon: LucideIcons.Airplay },
    { icon: LucideIcons.AlertCircle },
    { icon: LucideIcons.AlertTriangle },
    { icon: LucideIcons.AlignCenter },
    { icon: LucideIcons.AlignJustify },
    { icon: LucideIcons.AlignLeft },
    { icon: LucideIcons.AlignRight },
    { icon: LucideIcons.Anchor },
    { icon: LucideIcons.Aperture },
    { icon: LucideIcons.Archive },
    { icon: LucideIcons.ArrowDown },
    { icon: LucideIcons.ArrowDownCircle },
    { icon: LucideIcons.ArrowDownLeft },
    { icon: LucideIcons.ArrowDownRight },
    { icon: LucideIcons.ArrowLeft },
    { icon: LucideIcons.ArrowLeftCircle },
    { icon: LucideIcons.ArrowRight },
    { icon: LucideIcons.ArrowRightCircle },
    { icon: LucideIcons.ArrowUp },
    { icon: LucideIcons.ArrowUpCircle },
    { icon: LucideIcons.ArrowUpLeft },
    { icon: LucideIcons.ArrowUpRight },
    { icon: LucideIcons.AtSign },
    { icon: LucideIcons.Award },
    { icon: LucideIcons.BarChart },
    { icon: LucideIcons.BarChart2 },
    { icon: LucideIcons.Battery },
    { icon: LucideIcons.BatteryCharging },
    { icon: LucideIcons.Bell },
    { icon: LucideIcons.Bluetooth },
    { icon: LucideIcons.Bold },
    { icon: LucideIcons.Book },
    { icon: LucideIcons.BookOpen },
    { icon: LucideIcons.Bookmark },
    { icon: LucideIcons.Box },
    { icon: LucideIcons.Briefcase },
    { icon: LucideIcons.Calendar },
    { icon: LucideIcons.Camera },
    { icon: LucideIcons.CameraOff },
    { icon: LucideIcons.Cast },
    { icon: LucideIcons.Check },
    { icon: LucideIcons.CheckCircle },
    { icon: LucideIcons.CheckSquare },
    { icon: LucideIcons.ChevronDown },
    { icon: LucideIcons.ChevronLeft },
    { icon: LucideIcons.ChevronRight },
    { icon: LucideIcons.ChevronUp },
    { icon: LucideIcons.ChevronsDown },
    { icon: LucideIcons.ChevronsLeft },
    { icon: LucideIcons.ChevronsRight },
    { icon: LucideIcons.ChevronsUp },
    { icon: LucideIcons.Chrome },
    { icon: LucideIcons.Circle },
    { icon: LucideIcons.Clipboard },
    { icon: LucideIcons.Clock },
    { icon: LucideIcons.Cloud },
    { icon: LucideIcons.CloudDrizzle },
    { icon: LucideIcons.CloudLightning },
    { icon: LucideIcons.CloudOff },
    { icon: LucideIcons.CloudRain },
    { icon: LucideIcons.CloudSnow },
    { icon: LucideIcons.Code },
    { icon: LucideIcons.Codepen },
    { icon: LucideIcons.Codesandbox },
    { icon: LucideIcons.Coffee },
    { icon: LucideIcons.Columns },
    { icon: LucideIcons.Command },
    { icon: LucideIcons.Compass },
    { icon: LucideIcons.Copy },
    { icon: LucideIcons.CornerDownLeft },
    { icon: LucideIcons.CornerDownRight },
    { icon: LucideIcons.CornerLeftDown },
    { icon: LucideIcons.CornerLeftUp },
    { icon: LucideIcons.CornerRightDown },
    { icon: LucideIcons.CornerRightUp },
    { icon: LucideIcons.CornerUpLeft },
    { icon: LucideIcons.CornerUpRight },
    { icon: LucideIcons.Cpu },
    { icon: LucideIcons.CreditCard },
    { icon: LucideIcons.Crop },
    { icon: LucideIcons.Crosshair },
    { icon: LucideIcons.Database },
    { icon: LucideIcons.Delete },
    { icon: LucideIcons.Disc },
    { icon: LucideIcons.Divide },
    { icon: LucideIcons.DivideCircle },
    { icon: LucideIcons.DivideSquare },
    { icon: LucideIcons.DollarSign },
    { icon: LucideIcons.Download },
    { icon: LucideIcons.Dribbble },
    { icon: LucideIcons.Droplet },
    { icon: LucideIcons.Edit },
    { icon: LucideIcons.Edit2 },
    { icon: LucideIcons.Edit3 },
    { icon: LucideIcons.ExternalLink },
    { icon: LucideIcons.Eye },
    { icon: LucideIcons.EyeOff },
    { icon: LucideIcons.Facebook },
    { icon: LucideIcons.FastForward },
    { icon: LucideIcons.Feather },
    { icon: LucideIcons.Figma },
    { icon: LucideIcons.File },
    { icon: LucideIcons.FileMinus },
    { icon: LucideIcons.FilePlus },
    { icon: LucideIcons.FileText },
    { icon: LucideIcons.Film },
    { icon: LucideIcons.Filter },
    { icon: LucideIcons.Flag },
    { icon: LucideIcons.Folder },
    { icon: LucideIcons.FolderMinus },
    { icon: LucideIcons.FolderPlus },
    { icon: LucideIcons.Framer },
    { icon: LucideIcons.Frown },
    { icon: LucideIcons.Fullscreen },
    { icon: LucideIcons.Gift },
    { icon: LucideIcons.GitBranch },
    { icon: LucideIcons.GitCommit },
    { icon: LucideIcons.GitMerge },
    { icon: LucideIcons.GitPullRequest },
    { icon: LucideIcons.Gitlab },
    { icon: LucideIcons.Globe },
    { icon: LucideIcons.Grid },
    { icon: LucideIcons.HardDrive },
    { icon: LucideIcons.Hash },
    { icon: LucideIcons.Headphones },
    { icon: LucideIcons.Heart },
    { icon: LucideIcons.HelpCircle },
    { icon: LucideIcons.Hexagon },
    { icon: LucideIcons.Home },
    { icon: LucideIcons.Image },
    { icon: LucideIcons.Inbox },
    { icon: LucideIcons.Info },
    { icon: LucideIcons.Instagram },
    { icon: LucideIcons.Italic },
    { icon: LucideIcons.Key },
    { icon: LucideIcons.Layers },
    { icon: LucideIcons.Layout },
    { icon: LucideIcons.LifeBuoy },
    { icon: LucideIcons.Link },
    { icon: LucideIcons.Link2 },
    { icon: LucideIcons.Linkedin },
    { icon: LucideIcons.List },
    { icon: LucideIcons.Loader },
    { icon: LucideIcons.Lock },
    { icon: LucideIcons.LogIn },
    { icon: LucideIcons.LogOut },
    { icon: LucideIcons.Mail },
    { icon: LucideIcons.Map },
    { icon: LucideIcons.MapPin },
    { icon: LucideIcons.Maximize },
    { icon: LucideIcons.Maximize2 },
    { icon: LucideIcons.Meh },
    { icon: LucideIcons.Menu },
    { icon: LucideIcons.MessageCircle },
    { icon: LucideIcons.MessageSquare },
    { icon: LucideIcons.Mic },
    { icon: LucideIcons.MicOff },
    { icon: LucideIcons.Minimize },
    { icon: LucideIcons.Minimize2 },
    { icon: LucideIcons.Minus },
    { icon: LucideIcons.MinusCircle },
    { icon: LucideIcons.MinusSquare },
    { icon: LucideIcons.Monitor },
    { icon: LucideIcons.Moon },
    { icon: LucideIcons.MoreHorizontal },
    { icon: LucideIcons.MoreVertical },
    { icon: LucideIcons.MousePointer },
    { icon: LucideIcons.Move },
    { icon: LucideIcons.Music },
    { icon: LucideIcons.Navigation },
    { icon: LucideIcons.Navigation2 },
    { icon: LucideIcons.Octagon },
    { icon: LucideIcons.Package },
    { icon: LucideIcons.Paperclip },
    { icon: LucideIcons.Pause },
    { icon: LucideIcons.PauseCircle },
    { icon: LucideIcons.PenTool },
    { icon: LucideIcons.Percent },
    { icon: LucideIcons.Phone },
    { icon: LucideIcons.PhoneCall },
    { icon: LucideIcons.PhoneForwarded },
    { icon: LucideIcons.PhoneIncoming },
    { icon: LucideIcons.PhoneMissed },
    { icon: LucideIcons.PhoneOff },
    { icon: LucideIcons.PhoneOutgoing },
    { icon: LucideIcons.PieChart },
    { icon: LucideIcons.Play },
    { icon: LucideIcons.PlayCircle },
    { icon: LucideIcons.Plus },
    { icon: LucideIcons.PlusCircle },
    { icon: LucideIcons.PlusSquare },
    { icon: LucideIcons.Pocket },
    { icon: LucideIcons.Power },
    { icon: LucideIcons.Printer },
    { icon: LucideIcons.Radio },
    { icon: LucideIcons.RefreshCcw },
    { icon: LucideIcons.RefreshCw },
    { icon: LucideIcons.Repeat },
    { icon: LucideIcons.Rewind },
    { icon: LucideIcons.RotateCcw },
    { icon: LucideIcons.RotateCw },
    { icon: LucideIcons.Rss },
    { icon: LucideIcons.Save },
    { icon: LucideIcons.Scissors },
    { icon: LucideIcons.Search },
    { icon: LucideIcons.Send },
    { icon: LucideIcons.Server },
    { icon: LucideIcons.Settings },
    { icon: LucideIcons.Share },
    { icon: LucideIcons.Share2 },
    { icon: LucideIcons.Shield },
    { icon: LucideIcons.ShieldOff },
    { icon: LucideIcons.ShoppingBag },
    { icon: LucideIcons.ShoppingCart },
    { icon: LucideIcons.Shuffle },
    { icon: LucideIcons.Sidebar },
    { icon: LucideIcons.SkipBack },
    { icon: LucideIcons.SkipForward },
    { icon: LucideIcons.Slack },
    { icon: LucideIcons.Slash },
    { icon: LucideIcons.Sliders },
    { icon: LucideIcons.Smartphone },
    { icon: LucideIcons.Smile },
    { icon: LucideIcons.Speaker },
    { icon: LucideIcons.Square },
    { icon: LucideIcons.Star },
    { icon: LucideIcons.StopCircle },
    { icon: LucideIcons.Sun },
    { icon: LucideIcons.Sunrise },
    { icon: LucideIcons.Sunset },
    { icon: LucideIcons.Tablet },
    { icon: LucideIcons.Tag },
    { icon: LucideIcons.Target },
    { icon: LucideIcons.Terminal },
    { icon: LucideIcons.Thermometer },
    { icon: LucideIcons.ThumbsDown },
    { icon: LucideIcons.ThumbsUp },
    { icon: LucideIcons.ToggleLeft },
    { icon: LucideIcons.ToggleRight },
    { icon: LucideIcons.Trash },
    { icon: LucideIcons.Trash2 },
    { icon: LucideIcons.Trello },
    { icon: LucideIcons.TrendingDown },
    { icon: LucideIcons.TrendingUp },
    { icon: LucideIcons.Triangle },
    { icon: LucideIcons.Truck },
    { icon: LucideIcons.Tv },
    { icon: LucideIcons.Twitch },
    { icon: LucideIcons.Twitter },
    { icon: LucideIcons.Type },
    { icon: LucideIcons.Umbrella },
    { icon: LucideIcons.Underline },
    { icon: LucideIcons.Unlock },
    { icon: LucideIcons.Upload },
    { icon: LucideIcons.UploadCloud },
    { icon: LucideIcons.User },
    { icon: LucideIcons.UserCheck },
    { icon: LucideIcons.UserMinus },
    { icon: LucideIcons.UserPlus },
    { icon: LucideIcons.UserX },
    { icon: LucideIcons.Users },
    { icon: LucideIcons.Video },
    { icon: LucideIcons.VideoOff },
    { icon: LucideIcons.Voicemail },
    { icon: LucideIcons.Volume },
    { icon: LucideIcons.Volume1 },
    { icon: LucideIcons.Volume2 },
    { icon: LucideIcons.VolumeX },
    { icon: LucideIcons.Watch },
    { icon: LucideIcons.Wifi },
    { icon: LucideIcons.WifiOff },
    { icon: LucideIcons.Wind },
    { icon: LucideIcons.X },
    { icon: LucideIcons.XCircle },
    { icon: LucideIcons.XOctagon },
    { icon: LucideIcons.XSquare },
    { icon: LucideIcons.Youtube },
    { icon: LucideIcons.Zap },
    { icon: LucideIcons.ZapOff },
    { icon: LucideIcons.ZoomIn },
    { icon: LucideIcons.ZoomOut }
]
